[target.x86_64-pc-windows-gnu]
linker = "C:\\Users\\ssilk\\AppData\\Local\\Microsoft\\WinGet\\Packages\\MartinStorsjo.LLVM-MinGW.MSVCRT_Microsoft.Winget.Source_8wekyb3d8bbwe\\llvm-mingw-20260616-msvcrt-x86_64\\bin\\x86_64-w64-mingw32-clang.exe"
ar = "C:\\Users\\ssilk\\AppData\\Local\\Microsoft\\WinGet\\Packages\\MartinStorsjo.LLVM-MinGW.MSVCRT_Microsoft.Winget.Source_8wekyb3d8bbwe\\llvm-mingw-20260616-msvcrt-x86_64\\bin\\llvm-ar.exe"
rustflags = ["-C", "link-self-contained=no", "-C", "link-args=-fuse-ld=lld"]
